{% set version = "1.3.7" %}

package:
  name: crisprme
  version: {{ version }}

source:
  url: https://github.com/samuelecancellieri/CRISPRme/archive/v{{ version }}.tar.gz
  sha256: 8325ee1fa4e9223257279f110008aafd03458ebd7af8b5f80f042303c9219a69
  
build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >3.6
    - crispritz

test:
  commands:
    - crisprme.py

about:
  home: https://github.com/samuelecancellieri/CRISPRme
  license: GPL3
  license_file: LICENSE
  summary: CRISPRme, tool package for CRISPR experiments assessment and analysis.
