{% set version = "1.3.8" %}

package:
  name: crisprme
  version: {{ version }}

source:
  url: https://github.com/samuelecancellieri/CRISPRme/archive/v{{ version }}.tar.gz
  sha256: ef98f09ba22725fc26d3e7824b8e3d0532338c3c5d7c85f8b582822671e99226
  
build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >3.6
    - crispritz

test:
  commands:
    - crisprme.py

about:
  home: https://github.com/samuelecancellieri/CRISPRme
  license: GPL3
  license_file: LICENSE
  summary: CRISPRme, tool package for CRISPR experiments assessment and analysis.
